global:
  postgresql:
    auth:
      existingSecret: postgres-secret
      postgresqlUsernameKey: postgres-username
      postgresqlPasswordKey: postgres-password
      postgressqlDatabase: "budgetapp"
  repmgr:
    existingSecret: postgres-secret
    repmgrPasswordKey: repmgr-password

pgpool:
  adminUsername: postgres-username
  adminPassword: postgres-password
  replicationUsername: replication-username
  replicationPasswordKey: replication-password

primary:
  persistence:
    enabled: true
    storageClass: "microk8s-hostpath"
    size: 2Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 1000m

standby:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "microk8s-hostpath"
    size: 8Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 1000m

service:
  type: ClusterIP
  port: 5432

replication:
  enabled: true
  applicationName: database-replication
  username: replication-user
  passwordKey: replication-password
  numSynchronousReplicas: 1

postgresql:
  sharedBuffers: "256MB"
  maxConnections: 10

backup:
  enabled: false
  storageClass: "microk8s-hostpath"
  backupDir: /backups
