image:
  repository: postgres
  tag: "13.4"

pgpool:
  enabled: true
  image: "registry.developers.arm.com/pgpool/pgpool:4.2.4"

database:
  name: budgetapp
  usernameSecretKey: POSTGRES_USER
  passwordSecretKey: POSTGRES_PASSWORD

secret:
  name: postgres-secrets-budgetapp

namespace: database
storage:
  size: 2Gi
