apiVersion: v1
kind: ConfigMap
metadata:
  name: budgetapp-backend-config
  namespace: budgetapp
data:
  DB_HOST: budgetapp-postgres.database.svc.cluster.local
  DB_NAME: budgetapp
  DB_PORT: "5432"
  IP_RESTRICTION_ENABLED: "false"
  ALLOWED_REGISTER_IP: "192.168.1.1/99"
  PORT: "8080"
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {
      server {
        location ^~ /.well-known/acme-challenge/ {
          default_type "text/plain";
          rewrite /.well-known/acme-challenge/(.*) /$1 break;
        }
      }
    }
