apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgetapp-ingress
  namespace: budgetapp
  annotations:
    cert-manager.io/cluster-issuer: "lets-encrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Enable SSL redirection for all paths
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ^~ /.well-known/acme-challenge/ {
          allow all;
          auth_basic off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_pass http://$host$request_uri;
          add_header Content-Type "text/plain";
          return 200;
      }
spec:
  rules:
    - host: budgetapp.hagh.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budgetapp-service
                port:
                  number: 80
  tls:
    - hosts:
        - budgetapp.hagh.dk
      secretName: budgetapp-tls

