apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgetapp-ingress
  namespace: budgetapp
  annotations:
    cert-manager.io/cluster-issuer: "lets-encrypt"  # Use the correct ClusterIssuer
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /.well-known/acme-challenge/ {
          allow all;
          default_type "text/plain";
          root /var/www/acme-challenge;
      }
spec:
  tls:
    - hosts:
        - budgetapp.hagh.dk
      secretName: budgetapp-tls-secret  # Optional, for HTTPS
  rules:
    - host: budgetapp.hagh.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budgetapp-budgetapp-backend
                port:
                  number: 80  # This is mapped to port 8081 in the service
