apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgetapp-ingress
  namespace: budgetapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - budgetapp.hagh.dk
      secretName: budgetapp-tls-secret  # Optional, for HTTPS
  rules:
    - host: budgetapp.hagh.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budgetapp-postgres
                port:
                  number: 80  # This is mapped to port 8081 in the service
