apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgetapp-ingress
  namespace: budgetapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: budgetapp.hagh.dk  # Replace with your desired domain or IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budgetapp-budgetapp-backend  # Replace with your service name
                port:
                  number: 8081  # Port your service is exposed on
