apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgetapp-ingress
  namespace: database
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: budgetapp.hagh.dk  # Replace with your desired domain or IP
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budgetapp-api-service  # Replace with your service name
                port:
                  number: 80  # Port your service is exposed on
