apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgetapp-ingress
  namespace: budgetapp
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production-pi"
    kubernetes.io/ingress.class: public
spec:
  rules:
    - host: budgetapp.hagh.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budgetapp-budgetapp-backend
                port:
                  number: 80
  tls:
    - hosts:
       - budgetapp.hagh.dk
      secretName: budgetapp-tls
