apiVersion: v1
kind: Service
metadata:
  name: {{ include "budgetapp-backend.fullname" . }}  # Ensure this line exists and generates a name
  labels:
    {{- include "budgetapp-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
  selector:
    app: {{ include "budgetapp-backend.name" . }}  # Ensure this matches the app selector
