image:
  repository: postgres
  tag: "13.16"
secret:
  name: postgres-secret
database:
  name: default
  usernameSecretKey: POSTGRES_USER
  passwordSecretKey: POSTGRES_PASSWORD
pgpool:
  enabled: true
  admin:
    usernameSecretKey: PGPOOL_ADMIN_USER
    passwordSecretKey: PGPOOL_ADMIN_PASSWORD
  replication:
    userSecretKey: REPLICATION_USER
    passwordSecretKey: REPLICATION_PASSWORD
replication:
  enabled: true
  userSecretKey: REPLICATION_USER
  passwordSecretKey: REPLICATION_PASSWORD
storage:
  size: 2Gi
