apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.database.name }}-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: {{ .Values.database.name }}
  POSTGRES_USER: {{ .Values.database.username }}
