apiVersion: v1
kind: PersistentVolume
metadata:
  name: budgetapp-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast-storage  # Must match the PVC storageClassName
  hostPath:
    path: "/home/morten/pv/budgetapp"  # Ensure this path exists on the host node
