apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ .Values.database.name }}-postgres
