image:
  repository: postgres:alpine
  tag: "3.20"
secret:
  name: postgres-secret
pgpool:
  enabled: true
  image: "registry.developers.arm.com/pgpool/pgpool:4.2.4"
  admin:
    usernameSecretKey: PGPOOL_ADMIN_USER
    passwordSecretKey: PGPOOL_ADMIN_PASSWORD
  replication:
    userSecretKey: REPLICATION_USER
    passwordSecretKey: REPLICATION_PASSWORD
replication:
  enabled: true
  userSecretKey: REPLICATION_USER
  passwordSecretKey: REPLICATION_PASSWORD
storage:
  size: 2Gi
